config/routes.rb
Skeleton::Application.routes.draw do




  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins

  resources :contacts
  resources :posts, :as =>:news
  resources :galleries

  namespace "admin" do
    resources :partners    
    resources :staffs
    resources :posts  do 
      resources :albums
    end
    resources :categories
    

    resources :products do 
      resources :albums
    end
    resources :contacts
    resources :pages do 
      resources :albums
    end
    resources :albums do 
      resources :uploads
    end
    match '/update_category' =>"categories#update_categories", :as => :update_categories
    
    match '/update_product_category' =>"products#update_product_categories", :as => :update_product_categories
    match '/update_post_category' =>"posts#update_post_categories", :as => :update_post_categories
    root :to => "overview#index"
  end 
  
  match "/gallery" => "galleries#index", :as => :galleries
  match "/category/:parent(subcategory/:category(/filter/:subcategory))" => "posts#index",:as =>:post_filtered
  match "/tag/:tag" => "posts#index", :as => :posts
  match "/:name" => "viewer#show", :as => :viewer
  root :to => "viewer#show", :name => "home"
  #root :to => 'home#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :title, :description, :albumable_id, :albumable_type, :position, :category_id

   belongs_to :albumable, :polymorphic => true

   has_many :uploads, :dependent => :destroy

   belongs_to :category
   # attr_accessible :uploads_attributes 
   #   attr_writer :uploads_attributes
   #   accepts_nested_attributes_for :uploads, :reject_if => lambda { |a| a[:title].blank? }, :allow_destroy => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :parent_id, :position, :description, :name,:navlabel
  has_many :posts
  has_many :albums
  has_many :subcategories, :class_name => 'Category', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'Category', :foreign_key => 'parent_id'

  has_one :metatag, :as => :metatagable,  :dependent => :destroy
  attr_accessible :metatag_attributes 
  attr_writer :metatag_attributes
  accepts_nested_attributes_for :metatag
  
  def self.find_main
     Category.order("position").where("parent_id IS ?", nil).all
   end
   def self.find_sub(pid)
     Category.order("position").where('parent_id = ?', pid).all
   end
   def self.find_all_sub
     Category.order("position").where('parent_id IS NOT ?', nil).all
   end

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/metatag.rb
class Metatag < ActiveRecord::Base
  attr_accessible :title, :description,:keywords, :metatagable_id, :metatagable_type
  validates_presence_of :title, :description,:keywords
  belongs_to :metatagable, :polymorphic => true
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title, :navlabel,:name,:published, :position, :body, :image
  
  validates_presence_of :title, :navlabel
  validates_uniqueness_of :title
  
  mount_uploader :image, ImageUploader
  
  
  has_one :metatag, :as => :metatagable,  :dependent => :destroy
  attr_accessible :metatag_attributes 
  attr_writer :metatag_attributes
  accepts_nested_attributes_for :metatag
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  attr_accessible :name,:website, :bio,:industry,:twitter, :logo, :position, :parnter_since, :partner_url
  mount_uploader :logo, ImageUploader
  validates_presence_of :name
  validates_presence_of :website
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :name,:title,:tag_list, :body,:category_id, :published,:published_on, :start_at, :end_date, :end_at, :image
  
  belongs_to :category
  mount_uploader :image, ImageUploader
  
  acts_as_taggable
  acts_as_taggable_on :tags
  has_one :metatag, :as => :metatagable,  :dependent => :destroy
  attr_accessible :metatag_attributes 
  attr_writer :metatag_attributes
  accepts_nested_attributes_for :metatag
  
  has_many :albums, :as => :albumable, :dependent => :destroy
  
  scope :published, where(:published => true).order("published_on DESC")
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :category_id,:description,:tagline, :published
  belongs_to :category
  
  has_one :metatag, :as => :metatagable,  :dependent => :destroy
  attr_accessible :metatag_attributes 
  attr_writer :metatag_attributes
  accepts_nested_attributes_for :metatag
  
  has_many :albums, :as => :albumable, :dependent => :destroy
end

app/models/staff.rb
require 'file_size_validator' 
class Staff < ActiveRecord::Base
  attr_accessible :name,:surname, :bio,:role,:twitter, :image, :position, :started_on
  mount_uploader :image, ImageUploader
  validates_presence_of :name
  validates_presence_of :surname
end

app/models/upload.rb
require 'file_size_validator' 
class Upload < ActiveRecord::Base
  attr_accessible :title, :description, :photo,:crop_x,:crop_y, :crop_h, :crop_w,:album_id, :image, :position
  mount_uploader :image, ImageUploader
  belongs_to :album
  
  validates_presence_of :title, :image
  # attr_accessor  :crop_x, :crop_y, :crop_h, :crop_w
  #   after_update :reprocess_image, :if => :cropping?
  # 
  #   def image=(obj)
  #     super(obj)
  #     # Put your callbacks here, e.g.
  #     self.image = false  
  #   end
  # 
  #    validates :image, 
  #        :file_size => { 
  #          :maximum => 2.megabytes.to_i 
  #        }
  # 
  #    def cropping?
  #      !crop_x.blank? && !crop_y.blank?  && !crop_w.blank? && !crop_h.blank?
  #    end
  #    #     
  #    def image_geometry
  #      img = MiniMagick::Image.open("public"+self.image_url)
  #      @geometry = {:width => img[:width], :height => img[:height] }
  #    end
  #    # 
  #    private
  # 
  # 
  #    def reprocess_image
  #        image = MiniMagick::Image.from_file("public"+self.image.url)
  #        crop_params = "#{crop_w}x#{crop_h}+#{crop_x}+#{crop_y}"
  #        image.crop(crop_params)
  #        image
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/viewer_helper.rb
module ViewerHelper
end

app/views/admin/pages/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.page.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :navlabel, t("activerecord.attributes.page.navlabel", :default => "Navlabel"), :class => :label %>
    <%= f.text_field :navlabel, :class => 'text_field validate[required] ' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :name, t("activerecord.attributes.page.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :published, t("activerecord.attributes.page.published", :default => "Published"), :class => :label %>
    <%= f.check_box :published, :class => 'check_box ' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :body, t("activerecord.attributes.page.body", :default => "Body"), :class => :label %>
    <%= f.cktext_area  :body,:toolbar => 'Easy', :input_html =>{:class => 'text_area'} %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :image, t("activerecord.attributes.page.image", :default => "Image"), :class => :label %>
    <%= f.file_field :image, :class => 'file_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :position, t("activerecord.attributes.page.position", :default => "Position"), :class => :label %>
 		<%= f.select :position,1..20, {:class => 'number_field validate[required]',:include_blank => "Not Defined"} %>
    <span class="description">Ex: Home.jpg</span>
  </div>
 <h1>Metatag</h1>
	<%= f.simple_fields_for :metatag, @page.metatag do |builder| %>
	 <%= render "shared/form/metatag_fields", :f => builder %>
	<% end %>
	       
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_pages_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/pages/_metatag_fields.html.erb
<div class="fields">
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.page.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
 <div class="group">
    <%= f.label :description, t("activerecord.attributes.page.body", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area' %>
    <span class="description">Ex: a simple description</span>
  </div>
 <div class="group">
    <%= f.label :keywords, t("activerecord.attributes.page.body", :default => "Keywords"), :class => :label %>
    <%= f.text_area :keywords, :class => 'text_area' %>
    <span class="description">Ex: a simple list of keywords</span>
  </div>
	<%= f.input :metatagable_id, :as => :hidden %>
	<%= f.input :metatagable_type, :as => :hidden %>


</div>

app/views/admin/pages/_page.html.erb
 <tr class="<%= cycle("odd", "even") %>">
    <td>
      <%= page.id %>
    </td>
    <td>
      <%= page.name %>
    </td>
    <td>
      <%= link_to page.title, admin_page_path(page) %>
    </td>
    <td>
      <%= page.created_at %>
    </td>
    <td class="last">
      <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_page_path(page) %> |
      <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_page_path(page) %> |
      <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_page_path(page), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
  </tr>

app/views/admin/pages/_sidebar.html.erb
<div class="block notice">
  <h3>Page Manager</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/pages/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_pages_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_page_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_page_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Page</h2>
    <div class="inner">
      <%= form_for @page, :url => admin_page_path(@page), :html => { :class => :form, :multipart => true } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

<% content_for(:scripts) do %>
<script type="text/javascript">
	$(function() {
		//alert("fck yeah");
		$(".form").validationEngine();
	});
</script>
<% end %>

app/views/admin/pages/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_pages_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_page_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Pages</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
					<th>Name</th>
                    <th>
            <%= t("activerecord.attributes.page.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
          <%= render :partial => @pages %> 
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/pages/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_pages_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_page_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Page</h2>
    <div class="inner">
      <%= form_for([:admin,@page], :html => { :class => :form, :multipart => true }) do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>



<% content_for(:scripts) do %>
<script type="text/javascript">
	$(function() {
		//alert("fck yeah");
		$(".form").validationEngine();
	});
</script>
<% end %>

app/views/admin/pages/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_pages_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_page_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_page_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      <h1>Page Details</h1>
        <p>
          <b><%= t("activerecord.attributes.page.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @page.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.page.navlabel", :default => t("activerecord.labels.navlabel", :default => "Navlabel")) %>:</b>
          <%= @page.navlabel %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.page.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @page.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.page.published", :default => t("activerecord.labels.published", :default => "Published")) %>:</b>
          <%= @page.published %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.page.body", :default => t("activerecord.labels.body", :default => "Body")) %>:</b>
          <%= @page.body.html_safe %>
        </p>
        <p>
          <b><%= t("activerecord.attributes.page.position", :default => t("activerecord.labels.position", :default => "Position")) %>:</b>
          <%= @page.position %>
        </p>
        <p>
          <b><%= t("activerecord.attributes.page.image", :default => t("activerecord.labels.image", :default => "Image")) %>:</b>
          <%= image_tag @page.image, :width => 50 unless @page.image_url.blank? %>
        </p>
<% if @page.metatag %>
<h1>Metatags</h1>
        <p>
          <b><%= t("activerecord.attributes.metatag.title", :default => t("activerecord.labels.title", :default => "Metatitle")) %>:</b>
          <%= @page.metatag.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.metatag.description", :default => t("activerecord.labels.description", :default => "Metadescription")) %>:</b>
                   <%= @page.metatag.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.page.keywords", :default => t("activerecord.labels.keywords", :default => "Metakeywords")) %>:</b>
                 <%= @page.metatag.keywords %>
        </p>
<% end %>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_page_path(@page), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_page_path(@page), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/shared/_breadcrumbs.html.erb
<div id="breadcrumbs" class="container">
	<span class="left">
	<% unless @page and @page.name =="home" %>
		<%= link_to("Home",root_path)  %>	> 
	<% end %>
	<%= render_navigation :renderer => :text %>
	</span>
</div>

app/views/shared/_footer.html.erb
 <span class="left">Briesestr 9, Neukölln, Berlin. U7 Karl Marx Str. <b>Rag & Bone Man</b> © <%= Date.today.strftime("%Y") %>.</span>
	<span class="right">
	  Developed by <%= link_to "Feature Rich Ltd","http://www.featurerich.net" %>
</span>

app/views/shared/_side_foot.html.erb
					<ul class="footer">
						<li class="cloud">
							<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
							  <%= link_to tag.name, posts_path(tag.name), :class => css_class %>
							<% end %>
						</li>
						<li class="footer">
							<%= render :partial =>"shared/footer" %>		
						</li>
					</ul>

app/views/shared/form/_metatag_fields.html.erb
<div class="fields">
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.page.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>
 <div class="group">
    <%= f.label :description, t("activerecord.attributes.page.body", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area validate[required]' %>
    <span class="description">Ex: a simple description</span>
  </div>
 <div class="group">
    <%= f.label :keywords, t("activerecord.attributes.page.body", :default => "Keywords"), :class => :label %>
    <%= f.text_area :keywords, :class => 'text_area validate[required]' %>
    <span class="description">Ex: a simple list of keywords</span>
  </div>
	<%= f.input :metatagable_id, :as => :hidden %>
	<%= f.input :metatagable_type, :as => :hidden %>


</div>