config/routes.rb
Skeleton::Application.routes.draw do




  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins

  resources :contacts
  resources :posts, :as =>:news
  resources :galleries

  namespace "admin" do
    resources :partners    
    resources :staffs
    resources :posts  do 
      resources :albums
    end
    resources :categories
    

    resources :products do 
      resources :albums
    end
    resources :contacts
    resources :pages do 
      resources :albums
    end
    resources :albums do 
      resources :uploads
    end
    match '/update_category' =>"categories#update_categories", :as => :update_categories
    
    match '/update_product_category' =>"products#update_product_categories", :as => :update_product_categories
    match '/update_post_category' =>"posts#update_post_categories", :as => :update_post_categories
    root :to => "overview#index"
  end 
  
  match "/gallery" => "galleries#index", :as => :galleries
  match "/category/:parent(subcategory/:category(/filter/:subcategory))" => "posts#index",:as =>:post_filtered
  match "/tag/:tag" => "posts#index", :as => :posts
  match "/:name" => "viewer#show", :as => :viewer
  root :to => "viewer#show", :name => "home"
  #root :to => 'home#index'
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  attr_accessible :name,:website, :bio,:industry,:twitter, :logo, :position, :parnter_since, :partner_url
  mount_uploader :logo, ImageUploader
  validates_presence_of :name
  validates_presence_of :website
end

app/controllers/admin/partners_controller.rb
class Admin::PartnersController < Admin::BaseController
  # GET /partners
  # GET /partners.json
  def index
    @partners = Partner.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @partners }
    end
  end

  # GET /partners/1
  # GET /partners/1.json
  def show
    @partner = Partner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @partner }
    end
  end

  # GET /partners/new
  # GET /partners/new.json
  def new
    @partner = Partner.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @partner }
    end
  end

  # GET /partners/1/edit
  def edit
    @partner = Partner.find(params[:id])
  end

  # POST /partners
  # POST /partners.json
  def create
    @partner = Partner.new(params[:partner])

    respond_to do |format|
      if @partner.save
        format.html { redirect_to admin_partner_url(@partner), notice: 'Partner was successfully created.' }
        format.json { render json: @partner, status: :created, location: @partner }
      else
        format.html { render action: "new" }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /partners/1
  # PUT /partners/1.json
  def update
    @partner = Partner.find(params[:id])

    respond_to do |format|
      if @partner.update_attributes(params[:partner])
        format.html { redirect_to admin_partner_url(@partner), notice: 'Partner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /partners/1
  # DELETE /partners/1.json
  def destroy
    @partner = Partner.find(params[:id])
    @partner.destroy

    respond_to do |format|
      format.html { redirect_to admin_partners_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/views/admin/partners/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.partner.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :website, t("activerecord.attributes.partner.website", :default => "Website"), :class => :label %>
    <%= f.text_field :website, :class => 'text_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :twitter, t("activerecord.attributes.partner.twitter", :default => "Twitter"), :class => :label %>
    <%= f.text_field :twitter, :class => 'text_field ' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :bio, t("activerecord.attributes.partner.bio", :default => "Bio"), :class => :label %>
    <%= f.text_area :bio, :class => 'text_area validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :industry, t("activerecord.attributes.partner.industry", :default => "Industry"), :class => :label %>
    <%= f.text_field :industry, :class => 'text_field validate[required]' %>
    <span class="description">Ex: Online Marketing</span>
  </div>

  <div class="group">
    <%= f.label :position, t("activerecord.attributes.partner.position", :default => "Position"), :class => :label %>
     <%= f.select :position,1..20, :class => 'number_field' %>
    <span class="description">Ex: 1</span>
  </div>

  <div class="group">
    <%= f.label :parnter_since, t("activerecord.attributes.partner.parnter_since", :default => "Parnter since"), :class => :label %>
    <%= f.date_select :parnter_since, :class => 'datetime_select' %>
    <span class="description">Ex: 2012 May 18</span>
  </div>

  <div class="group">
    <%= f.label :logo, t("activerecord.attributes.partner.logo", :default => "Logo"), :class => :label %>
    <%= f.file_field :logo, :class => 'file_field validate[required]' %>
    <span class="description">Ex: Logo.png</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_partners_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/partners/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_partners_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_partner_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_partner_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Partner</h2>
    <div class="inner">
      <%= form_for @partner, :url => admin_partner_path(@partner), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>
<% content_for(:scripts) do %>
<script type="text/javascript">
	$(function() {
		//alert("fck yeah");
		$(".form").validationEngine();
	});
</script>
<% end %>

app/views/admin/partners/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_partners_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_partner_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Partners</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.admin_partner.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @partners.each do |partner| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= partner.id %>
          </td>
                    <td>
            <%= link_to partner.name, admin_partner_path(partner) %>
          </td>
                    <td>
            <%= partner.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_partner_path(partner) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_partner_path(partner) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_partner_path(partner), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/partners/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_partners_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_partner_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Partner</h2>
    <div class="inner">
      <%= form_for :partner, :url => admin_partners_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

<% content_for(:scripts) do %>
<script type="text/javascript">
	$(function() {
		//alert("fck yeah");
		$(".form").validationEngine();
	});
</script>
<% end %>

app/views/admin/partners/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_partners_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_partner_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_partner_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
        <%= image_tag @partner.logo, :style=>"margin-top:15px" %>
        <p>
          <b><%= t("activerecord.attributes.admin_partner.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @partner.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_partner.website", :default => t("activerecord.labels.website", :default => "Website")) %>:</b>
          <%= @partner.website %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_partner.twitter", :default => t("activerecord.labels.twitter", :default => "Twitter")) %>:</b>
          <%= @partner.twitter %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_partner.bio", :default => t("activerecord.labels.bio", :default => "Bio")) %>:</b>
          <%= @partner.bio %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_partner.industry", :default => t("activerecord.labels.industry", :default => "Industry")) %>:</b>
          <%= @partner.industry %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_partner.position", :default => t("activerecord.labels.position", :default => "Position")) %>:</b>
          <%= @partner.position %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_partner.parnter_since", :default => t("activerecord.labels.parnter_since", :default => "Parnter since")) %>:</b>
          <%= @partner.parnter_since %>
        </p>

 
       
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_partner_path(@partner), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_partner_path(@partner), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>