config/routes.rb
Skeleton::Application.routes.draw do




  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins

  resources :contacts
  resources :posts, :as =>:news
  resources :galleries

  namespace "admin" do
    resources :partners    
    resources :staffs
    resources :posts  do 
      resources :albums
    end
    resources :categories
    

    resources :products do 
      resources :albums
    end
    resources :contacts
    resources :pages do 
      resources :albums
    end
    resources :albums do 
      resources :uploads
    end
    match '/update_category' =>"categories#update_categories", :as => :update_categories
    
    match '/update_product_category' =>"products#update_product_categories", :as => :update_product_categories
    match '/update_post_category' =>"posts#update_post_categories", :as => :update_post_categories
    root :to => "overview#index"
  end 
  
  match "/gallery" => "galleries#index", :as => :galleries
  match "/category/:parent(subcategory/:category(/filter/:subcategory))" => "posts#index",:as =>:post_filtered
  match "/tag/:tag" => "posts#index", :as => :posts
  match "/:name" => "viewer#show", :as => :viewer
  root :to => "viewer#show", :name => "home"
  #root :to => 'home#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :parent_id, :position, :description, :name,:navlabel
  has_many :posts
  has_many :albums
  has_many :subcategories, :class_name => 'Category', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'Category', :foreign_key => 'parent_id'

  has_one :metatag, :as => :metatagable,  :dependent => :destroy
  attr_accessible :metatag_attributes 
  attr_writer :metatag_attributes
  accepts_nested_attributes_for :metatag
  
  def self.find_main
     Category.order("position").where("parent_id IS ?", nil).all
   end
   def self.find_sub(pid)
     Category.order("position").where('parent_id = ?', pid).all
   end
   def self.find_all_sub
     Category.order("position").where('parent_id IS NOT ?', nil).all
   end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    @metatag = @category.build_metatag
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    if @category.metatag.blank?
      @metatag = @category.build_metatag
    end
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to admin_category_path(@category), notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end
  
  def update_categories
     unless params[:id].blank?
       @category  = Category.find(params[:id])
      # @category = @subcategory.parent
       @subcategories = @category.subcategories   
     else 
        @category = nil
        @subcategories = Category.find_main
     end 
     respond_to do |format|
       format.js 
     end   
   end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
 <tr class="<%= cycle("odd", "even") %>">
    <td>
      <%= category.id %>
    </td>
    <td>
      <%= link_to category.name, admin_category_path(category) %>
    </td>
		<td>
			<%= category.parent.title unless category.parent.blank? %>
		</td>
    <td>
    	<%= category.created_at %>
    </td>
    <td class="last">
      <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_category_path(category) %> |
      <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_category_path(category) %> |
      <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_category_path(category), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
  </tr>

app/views/admin/categories/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.category.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :title, t("activerecord.attributes.category.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :navlabel, t("activerecord.attributes.category.navlabel", :default => "Navlabel"), :class => :label %>
    <%= f.text_field :navlabel, :class => 'text_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :parent_id, t("activerecord.attributes.category.parent_id", :default => "Parent"), :class => :label %>
    <%= f.select :parent_id, Category.find_main.map{|x|[" #{x.title}",x.id]},{:include_blank => 'blank (parent)'}, :class => 'number_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.category.description", :default => "Description"), :class => :label %>
    <%= f.cktext_area :description,:toolbar => 'Easy', :input_html =>{:class => 'text_area validate[required]'} %>
    <span class="description">Ex: a simple text</span>
  </div>

 <div class="group">
    <%= f.label :position, t("activerecord.attributes.page.position", :default => "Position"), :class => :label %>
    <%= f.select :position,1..20, :class => 'number_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

 <h1>Metatag</h1>
	<%= f.simple_fields_for :metatag, @category.metatag do |builder| %>
	 <%= render "shared/form/metatag_fields", :f => builder %>
	<% end %>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_categories_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/categories/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_category_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_category_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Category</h2>
    <div class="inner">
      <%= form_for @category, :url => admin_category_path(@category), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>
<% content_for(:scripts) do %>
<script type="text/javascript">
	$(function() {
		//alert("fck yeah");
		$(".form").validationEngine();
    $("#category_parent_id").change(function() {
      $.ajax({ type: 'POST', url: '<%= admin_update_categories_path %>', data: 'id='+this.value });
    });
	});
</script>
<% end %>

app/views/admin/categories/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_category_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Categories</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.admin_category.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
  				<th>Parent</th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
       <%= render :partial => @categories %>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/categories/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_categories_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_category_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Category</h2>
    <div class="inner">
      <%= form_for [:admin,@category], :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>
<% content_for(:scripts) do %>
<script type="text/javascript">
	$(function() {
		//alert("fck yeah");
		$(".form").validationEngine();
		$("#category_parent_id").change(function() {
			$.ajax({ type: 'POST', url: '<%= admin_update_categories_path %>', data: 'id='+this.value });
		});
	});
</script>
<% end %>

app/views/admin/categories/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_categories_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_category_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_category_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_category.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @category.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_category.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @category.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_category.navlabel", :default => t("activerecord.labels.navlabel", :default => "Navlabel")) %>:</b>
          <%= @category.navlabel %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_category.parent_id", :default => t("activerecord.labels.parent_id", :default => "Parent")) %>:</b>
          <%= @category.parent.title unless @category.parent.blank? %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_category.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @category.description %>
        </p>
				<% if @category.metatag %>
				<h1>Metatags</h1>
				        <p>
				          <b><%= t("activerecord.attributes.metatag.title", :default => t("activerecord.labels.title", :default => "Metatitle")) %>:</b>
				          <%= @category.metatag.title %>
				        </p>

				        <p>
				          <b><%= t("activerecord.attributes.metatag.description", :default => t("activerecord.labels.description", :default => "Metadescription")) %>:</b>
				                   <%= @category.metatag.description %>
				        </p>

				        <p>
				          <b><%= t("activerecord.attributes.page.keywords", :default => t("activerecord.labels.keywords", :default => "Metakeywords")) %>:</b>
				                 <%= @category.metatag.keywords %>
				        </p>
				<% end %>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_category_path(@category), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_category_path(@category), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/categories/update_categories.js.erb
//alert("<%= escape_javascript(options_for_select(@subcategories.map{|x| [x.title, x.id]})).html_safe %>");


<% unless @category == nil %>
$("#category_parent_id").html('<%= escape_javascript(options_for_select(@subcategories.map{|x| [" - #{x.title}", x.id]})).html_safe %>');

	<% if @category.parent.blank? #case its a parent  %>
	//
		$("#category_parent_id").append("<option value=''>Back</option>");
		$("#category_parent_id").prepend("<option selected value='<%= @category.id %>'><%= @category.title %></option>");
	<% elsif @category.parent.present? and @category.parent.parent.blank? # case its second level %>
	//
		$("#category_parent_id option").attr("disabled","disabled");
		$("#category_parent_id").append("<option value='<%= @category.parent.id %>'>Back</option>");
		$("#category_parent_id").prepend("<option selected value='<%= @category.id %>'><%= @category.title %></option>");

	<% elsif @category.parent.present? and @category.parent.parent.present? and @category.parent.parent.parent.blank? # case its third level %>
	//
		$("#category_parent_id").append("<option value='<%= @category.id %>'>Back</option>");
	<% end %>

<% else %>
$("#category_parent_id").html('<%= escape_javascript(options_for_select(@subcategories.map{|x| [" #{x.title}", x.id]})).html_safe %>');

$("#category_parent_id").prepend("<option selected value=''>None Selected</option>");
<% end %>