config/routes.rb
Skeleton::Application.routes.draw do




  mount Ckeditor::Engine => '/ckeditor'

  devise_for :admins

  resources :contacts
  resources :posts, :as =>:news
  resources :galleries

  namespace "admin" do
    resources :partners    
    resources :staffs
    resources :posts  do 
      resources :albums
    end
    resources :categories
    

    resources :products do 
      resources :albums
    end
    resources :contacts
    resources :pages do 
      resources :albums
    end
    resources :albums do 
      resources :uploads
    end
    match '/update_category' =>"categories#update_categories", :as => :update_categories
    
    match '/update_product_category' =>"products#update_product_categories", :as => :update_product_categories
    match '/update_post_category' =>"posts#update_post_categories", :as => :update_post_categories
    root :to => "overview#index"
  end 
  
  match "/gallery" => "galleries#index", :as => :galleries
  match "/category/:parent(subcategory/:category(/filter/:subcategory))" => "posts#index",:as =>:post_filtered
  match "/tag/:tag" => "posts#index", :as => :posts
  match "/:name" => "viewer#show", :as => :viewer
  root :to => "viewer#show", :name => "home"
  #root :to => 'home#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :title, :category_id,:description,:tagline, :published
  belongs_to :category
  
  has_one :metatag, :as => :metatagable,  :dependent => :destroy
  attr_accessible :metatag_attributes 
  attr_writer :metatag_attributes
  accepts_nested_attributes_for :metatag
  
  has_many :albums, :as => :albumable, :dependent => :destroy
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
         @product.albums.create(:title =>"First Album or Product #{@product.id}")
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end
  def update_product_categories
      unless params[:id].blank?
        @category  = Category.find(params[:id])
       # @category = @subcategory.parent
        @subcategories = @category.subcategories   
      else 
         @category = nil
         @subcategories = Category.find_main
      end 
      respond_to do |format|
        format.js 
      end   
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.product.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
	
    <%= f.label :category_id, t("activerecord.attributes.product.category_id", :default => "Category"), :class => :label %>
 
  	<%= f.select :category_id, Category.find_sub(7).map{|x|[" #{x.title}",x.id]},{:include_blank => 'None Selected'}, :class => 'number_field validate[required]' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :description, t("activerecord.attributes.product.description", :default => "Description"), :class => :label %>
    <%= f.text_area :description, :class => 'text_area' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :tagline, t("activerecord.attributes.product.tagline", :default => "Tagline"), :class => :label %>
    <%= f.text_field :tagline, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
  <div class="group">
    <%= f.label :published, t("activerecord.attributes.post.published", :default => "Published"), :class => :label %>
    <%= f.check_box :published, :class => 'check_box' %>
  </div>        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_products_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/products/_product.html.erb
 <tr class="<%= cycle("odd", "even") %>">
    <td>
      <%= product.id %>
    </td>

              <td>
      <%= link_to product.title, admin_product_path(product) %>
    </td>
    <td>
      <%= "#{product.category.parent.title} - #{product.category.title}" %>
    </td>
              <td>
      <%= product.created_at %>
    </td>
    <td class="last">
      <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_product_path(product) %> |
      <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_product_path(product) %> |
      <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_product_path(product), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %> |
			<%=  link_to "#{t("web-app-theme.albums", :default => "Albums")}", polymorphic_url([:admin,product, "albums"]) %>
    </td>
  </tr>

app/views/admin/products/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/admin/products/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Product</h2>
    <div class="inner">
      <%= form_for @product, :url => admin_product_path(@product), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>
<% content_for(:scripts) do %>
<script type="text/javascript">
	$(function() {
		//alert("fck yeah");
		$(".form").validationEngine();
		alert
			<% if @product.category.present? %>
			$("#product_category_id").html("<option selected value='<%= @product.category.id %>'><%= @product.category.title %></option>");
			//
			$("#product_category_id").append("<option value='<%= @product.category.parent.id %>'> Back  </option>");
			<% end %>
			$("#product_category_id").change(function() {
				$.ajax({ type: 'POST', url: '<%= admin_update_product_categories_path %>', data: 'id='+this.value });
			});
	});
</script>
<% end %>

app/views/admin/products/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Products</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.admin_product.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
					<th>Category</th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
     	<%= render :partial => @products %>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/products/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Product</h2>
    <div class="inner">
      <%= form_for :product, :url => admin_products_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>
<% content_for(:scripts) do %>
<script type="text/javascript">
	$(function() {
		//alert("fck yeah");
		$(".form").validationEngine();
		$("#product_category_id").change(function() {
			$.ajax({ type: 'POST', url: '<%= admin_update_product_categories_path %>', data: 'id='+this.value });
		});
	});
</script>
<% end %>

app/views/admin/products/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_product_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_product.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @product.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.category_id", :default => t("activerecord.labels.category_id", :default => "Category")) %>:</b>
          <%= @product.category_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @product.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.tagline", :default => t("activerecord.labels.tagline", :default => "Tagline")) %>:</b>
          <%= @product.tagline %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_product_path(@product), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_product_path(@product), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/products/update_product_categories.js.erb
//alert("<%= @category.subcategories.count %>");

<% unless @category.title == "Products" %>
$("#product_category_id").html('<%= escape_javascript(options_for_select(@subcategories.map{|x| [" - #{x.title}", x.id]})).html_safe %>');

	<% if @category.parent.present? and @category.parent.parent.blank?  %>
	//
		$("#product_category_id").append("<option value='<%= @category.parent_id %>'>Back</option>");
		$("#product_category_id").prepend("<option selected value='<%= @category.id %>'><%= @category.title %></option>");
	<% elsif  @category.parent.present? and @category.parent.parent.present? and @category.parent.parent.parent.blank? # case its second level %>
	//
		$("#product_category_id option").attr("disabled","disabled");
		$("#product_category_id").append("<option value='<%= @category.parent.id %>'>Back</option>");
		$("#product_category_id").prepend("<option selected value='<%= @category.id %>'><%= @category.title %></option>");


	<% end %>

<% else %>
$("#product_category_id").html('<%= escape_javascript(options_for_select(@subcategories.map{|x| [" #{x.title}", x.id]})).html_safe %>');

$("#product_category_id").prepend("<option selected value=''>None Selected</option>");
<% end %>